<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\CaseStudy;
use App\Models\Visit;

class UpdateCaseStudyContentSeeder extends Seeder
{
    protected function getCaseStudies(): array
    {
        return [
            [
                'title'   => 'The Reyes Family Crisis',
                'content' => '<p><strong>Background:</strong> Maria Reyes, a 34-year-old Latina woman, presents to your community mental health clinic following a referral from her primary care physician. She is accompanied by her mother, who speaks only Spanish. Maria reports experiencing intense sadness, tearfulness, and difficulty sleeping for the past six weeks, following the sudden death of her 8-year-old son in a car accident. She works as a nursing assistant and has been unable to return to work since the incident. Maria describes intrusive memories of the accident scene, nightmares, and a persistent sense of guilt — "If only I had been driving instead of my husband." Her husband, Eduardo, has reportedly become withdrawn and drinks heavily in the evenings. They have two other children, ages 5 and 11.</p><p><strong>Presenting Concerns:</strong> Complicated grief, possible PTSD, marital strain, parenting challenges, and occupational dysfunction. Maria denies active suicidal ideation but states, "Some days I wonder what the point of everything is." She has no prior mental health history and reports strong Catholic faith as a protective factor.</p><p><strong>Relevant History:</strong> Maria immigrated from Mexico at age 16. She completed her GED and nursing assistant certification in the US. She has a close extended family network but is reluctant to share her struggles due to fear of stigma. She drinks alcohol socially, 1–2 drinks per week, and denies illicit drug use.</p>',
            ],
            [
                'title'   => "Jordan's Identity Journey",
                'content' => '<p><strong>Background:</strong> Jordan, a 19-year-old non-binary college sophomore, self-refers to the university counseling center reporting anxiety, academic difficulties, and interpersonal conflicts with their roommate. Jordan identifies as pansexual and was recently rejected by their conservative family after coming out during winter break. They report feeling "like I do not exist to them anymore." Jordan describes difficulty concentrating in class, persistent worry about finances (they lost family financial support), disrupted sleep, muscle tension, and recurring panic attacks — particularly before exams.</p><p><strong>Presenting Concerns:</strong> Generalized anxiety with panic features, family estrangement, identity-related distress, and academic impairment. Jordan denies suicidal ideation but acknowledges a history of non-suicidal self-injury (cutting) two years ago, which they state they no longer engage in. They have one close friend on campus who is supportive.</p><p><strong>Relevant History:</strong> Jordan grew up in a rural, religiously conservative household. They excelled academically in high school. No formal prior mental health treatment. Reports experimenting with marijuana to manage anxiety — approximately 2–3 times per week. Jordan is concerned their grades will drop below the scholarship threshold and they will lose housing.</p>',
            ],
            [
                'title'   => 'The Nguyen Couple',
                'content' => '<p><strong>Background:</strong> Thanh, 47, and Linda, 44, a Vietnamese-American couple married for 18 years, present for couples counseling at their EAP provider referral. Thanh is a software engineer; Linda is a school teacher. They have three children (ages 8, 13, 17). The presenting complaint is escalating conflict over parenting, finances, and Linda disclosure that she had an emotional affair with a colleague 10 months ago, which she ended. Thanh reports feeling betrayed, humiliated, and unable to trust Linda. Linda reports she felt emotionally neglected for years and fell into the relationship accidentally. Both state they want to save the marriage for the sake of their children, but Thanh says he does not know if he can ever forgive her.</p><p><strong>Presenting Concerns:</strong> Infidelity and breach of trust, emotional disconnection, differentiated parenting styles (Thanh is authoritarian; Linda is permissive), financial stress related to the eldest son upcoming college costs, and cultural expectations around gender roles.</p><p><strong>Relevant History:</strong> Thanh immigrated from Vietnam at age 12 and experienced significant childhood poverty. Linda was born in the US. Both report alcohol use within normal limits. No history of domestic violence. Thanh has a history of depression managed with medication. Linda has never sought mental health services.</p>',
            ],
            [
                'title'   => 'Marcus: Trauma and Addiction',
                'content' => '<p><strong>Background:</strong> Marcus, a 28-year-old African-American male, is court-ordered to substance use counseling following a DUI arrest. He is a military veteran who served two combat tours in Afghanistan and was honorably discharged three years ago. Marcus reports drinking to manage flashbacks, hypervigilance, and nightmares. He consumes approximately 10–14 standard drinks per day and reports he has tried to stop twice but experienced severe withdrawal symptoms including tremors and sweating. He currently lives alone in a studio apartment, is unemployed, and has strained relationships with family. He presents with flat affect and minimal eye contact and states he is only present because the judge required it.</p><p><strong>Presenting Concerns:</strong> Alcohol Use Disorder (severe), PTSD related to combat trauma, unemployment, social isolation, and legal issues. Marcus denies current suicidal ideation but discloses a past attempt at age 25 via medication overdose, shortly after discharge. He reports no current therapeutic support and stopped taking his prescribed Prazosin medication six months ago.</p><p><strong>Relevant History:</strong> Marcus grew up in a low-income urban neighborhood. Witnessed gang-related violence as a child. Father was absent; mother died of cancer when he was 17. Joined the military at 18. No prior civilian criminal record. Past history of cannabis use; currently denies illicit drug use. VA has offered services but Marcus feels they are not helpful.</p>',
            ],
            [
                'title'   => 'Elena: Eating Disorder and Academic Pressure',
                'content' => '<p><strong>Background:</strong> Elena, a 22-year-old White female graduate student in biochemistry, is referred to the campus counseling center by her academic advisor after her GPA dropped significantly last semester. Elena presents as highly articulate but guarded. She reports that she has been restricting her food intake for approximately 14 months, initially describing it as clean eating. She currently consumes approximately 800–900 calories per day, exercises 2–3 hours daily, and is preoccupied with thoughts of food, weight, and body image. Her current BMI is 17.2. She denies purging behaviors. She reports episodes of light-headedness and difficulty concentrating.</p><p><strong>Presenting Concerns:</strong> Anorexia Nervosa (restricting type), perfectionism, academic decline, family conflict around expectations, and significant medical risk given low BMI. Elena parents are both physicians who expect her to complete her PhD and pursue research. Elena reports intense fear of gaining weight and distorted perception of her body.</p><p><strong>Relevant History:</strong> Strong family history of anxiety (mother, maternal grandmother). Elena reports her parents marriage was tense and she learned to be perfect to avoid conflict. No prior mental health treatment. Denies substance use. Active social media user who follows several fitness influencer accounts. Has a boyfriend who has expressed concern about her weight loss.</p>',
            ],
            [
                'title'   => 'Adolescent Depression in a Rural Community',
                'content' => '<p><strong>Background:</strong> Tyler, a 15-year-old White male, is brought to a rural community mental health center by his mother following his school recommendation after he turned in a dark essay in English class. Tyler is a sophomore who previously earned good grades but has declined academically over the past five months. He describes persistent low mood, lack of interest in football (previously his main activity), hypersomnia (sleeping 12–14 hours on weekends), low energy, and feelings of hopelessness. When asked about suicidal thoughts, Tyler initially denies, then admits to sometimes thinking about not waking up but denies a specific plan or intent.</p><p><strong>Presenting Concerns:</strong> Major Depressive Disorder (provisional), passive suicidal ideation, academic decline, and social withdrawal. Tyler father lost his job six months ago at the local coal plant closure and the family is experiencing financial hardship. There is increased tension at home. Tyler older brother left for college, and Tyler describes feeling left behind.</p><p><strong>Relevant History:</strong> No prior mental health treatment. Paternal grandmother had depression and completed suicide when Tyler was 9. Tyler is aware of this history. Mother reports Tyler had a period of adjustment difficulties around age 10 following a move. No substance use reported. Tyler participates willingly in the session once rapport is established.</p>',
            ],
            [
                'title'   => 'Priya: Culturally Complex Anxiety',
                'content' => '<p><strong>Background:</strong> Priya, a 31-year-old South Asian woman, presents voluntarily to an outpatient clinic describing extreme worry and physical tension. She is a second-generation Indian-American working as a financial analyst. Priya was recently engaged in an arranged marriage facilitated by her parents. She reports feeling overwhelmed by pressure from both sets of families regarding wedding planning, financial decisions, and expectations about moving and having children. She describes restlessness, difficulty concentrating at work, fatigue, irritability, and near-daily muscle headaches for approximately eight months. She has been catastrophizing about her relationship.</p><p><strong>Presenting Concerns:</strong> Generalized Anxiety Disorder, cultural identity conflict (Western autonomy values vs. collectivist family norms), relational uncertainty, and occupational impairment. Priya denies depression, suicidal ideation, or substance use. She reports strong familial and cultural expectations to marry and produce grandchildren, which conflicts with her personal desire for career advancement and delayed family planning.</p><p><strong>Relevant History:</strong> Priya has never sought mental health treatment before and notes that in her culture these things are not discussed openly. She reports her fiance is caring and respectful, but acknowledges limited pre-engagement time together. She has a history of academic perfectionism. Priya practices Hinduism and finds meditation somewhat helpful.</p>',
            ],
            [
                'title'   => 'Workplace Trauma: Dr. Hassan',
                'content' => '<p><strong>Background:</strong> Dr. Kareem Hassan, a 50-year-old Egyptian-American emergency medicine physician, is referred for an EAP assessment following a complaint by a hospital colleague about increasing emotional outbursts and one instance of throwing a clipboard in the break room. Dr. Hassan presents reluctantly, emphasizing he is not mentally ill and attributes his behavior to systemic hospital understaffing. He describes sleeping 4–5 hours per night due to overnight shifts, persistent irritability, difficulty switching off after traumatic patient deaths, and diminished enjoyment of previously enjoyed activities such as chess and family dinners. He denies sadness but acknowledges numbness.</p><p><strong>Presenting Concerns:</strong> Occupational burnout with possible secondary traumatic stress or PTSD features, sleep disruption, emotional dysregulation, and relationship strain with spouse who has threatened separation. Dr. Hassan has witnessed three in-shift patient deaths in the past month, including a child. He minimizes the impact, stating that death is part of the job. Denies suicidal ideation.</p><p><strong>Relevant History:</strong> No prior mental health history. Graduated top of his medical school class in Egypt; immigrated for residency. Drinks 2–4 units of scotch nightly to unwind. Denies other substance use. Two adult children from a prior marriage; currently married 12 years. Reports strained connection with spouse.</p>',
            ],
            [
                'title'   => 'Child Witness: Aaliyah',
                'content' => '<p><strong>Background:</strong> Aaliyah, a 7-year-old Black girl, is brought to a play therapy assessment by her maternal grandmother, who has temporary guardianship. Three months ago, Aaliyah witnessed her mother partner physically assault her mother in the home. The partner has since been arrested and the mother is in a domestic violence shelter. Aaliyah was removed to grandmother care by CPS. Grandmother reports that Aaliyah has regressed significantly: she has started wetting the bed, refuses to sleep alone, cries frequently without apparent cause, and displays aggressive behavior at school. Aaliyah teacher reports she has become hypervigilant and easily startled by loud noises.</p><p><strong>Presenting Concerns:</strong> Pediatric PTSD following exposure to domestic violence, separation from primary caregiver, adjustment difficulties, and regression. Aaliyah demonstrates hyperarousal, avoidance, and intrusive re-experiencing symptoms consistent with trauma. Grandmother reports ongoing contact with mother via supervised phone calls, which appear dysregulating to Aaliyah.</p><p><strong>Relevant History:</strong> No prior mental health treatment. Aaliyah was described as a bright, social child prior to the incident. Currently in second grade. Inconsistent school attendance over the past two years during period of domestic instability. Grandmother reports the family has limited financial resources and transportation is a barrier to consistent therapy attendance.</p>',
            ],
            [
                'title'   => 'Late-Life Depression: Mr. Kowalski',
                'content' => '<p><strong>Background:</strong> Harold Kowalski, a 74-year-old White male, is referred by his internist following a routine appointment where he disclosed that his wife of 49 years passed away four months ago. Harold comes to the first session wearing his Sunday best and is notably polite and formal. He describes his presenting problem as simply needing to get his act together. He reports low motivation, difficulty completing household tasks he and his wife shared, social isolation, significant weight loss (18 lbs in four months), early morning awakening, and a general sense that the world has lost its color.</p><p><strong>Presenting Concerns:</strong> Major Depressive Disorder following bereavement, malnutrition risk, social withdrawal, and functional decline. When asked directly about suicidal ideation, Harold pauses and notes the religious and cultural barriers to such thoughts. He does not fully deny passive ideation. He lives alone in their family home; adult children live in other states.</p><p><strong>Relevant History:</strong> Retired machinist. No prior mental health treatment. Moderate alcohol use during marriage (1–2 beers nightly); reports drinking has increased to 3–4 nightly since wife death. Strong Catholic faith. Reports good physical health aside from managed hypertension and Type 2 diabetes. Drives independently. Computer-literate and communicates with grandchildren via email.</p>',
            ],
            [
                'title'   => 'Transgender Youth: Alex',
                'content' => '<p><strong>Background:</strong> Alex, a 16-year-old assigned-female-at-birth transgender male, is referred to an outpatient therapist by a pediatrician following disclosure of depression and self-harm. Alex has been presenting as male since age 13 and uses he/him pronouns. He lives with his mother (supportive) and stepfather (dismissive of his gender identity). Alex reports depressed mood, cutting on his upper arms since age 14, social anxiety, and persistent dysphoria related to his body. He was recently denied gender-affirming care by his stepfather, who has medical decision-making authority. Alex states he does not know how much longer he can live in this situation.</p><p><strong>Presenting Concerns:</strong> Major Depressive Disorder with active non-suicidal self-injury (NSSI), gender dysphoria, family conflict, restricted access to affirming healthcare, and elevated suicide risk given cumulative minority stress factors. Alex denies a specific plan but expresses hopelessness about the future. School performance has declined significantly.</p><p><strong>Relevant History:</strong> Alex has one affirming friend group at school and is part of the school GSA. He has been in therapy twice before but discontinued when therapists were not knowledgeable about transgender issues. Reports marijuana use 1–2 times monthly. No prior hospitalization. Mother is in couples counseling with stepfather. Alex has regular contact with his biological father who is partially supportive.</p>',
            ],
        ];
    }

    protected function getVisitTemplates(): array
    {
        return [
            [
                'title_suffix' => 'Visit 1 – Initial Assessment',
                'description'  => '<p><strong>Session Context:</strong> This is the client first clinical contact. The counselor primary tasks include establishing rapport, obtaining informed consent, completing a bio-psychosocial intake assessment, conducting a risk screen, and forming a preliminary case conceptualization. The client may be guarded, ambivalent, or in crisis. Prioritize safety first, then alliance building.</p><p><strong>Key Counselor Tasks:</strong> Greet and orient the client to the counseling process. Explain confidentiality and its limits including duty to warn and mandatory reporting. Explore the presenting problem using open-ended questions. Obtain relevant history covering developmental, medical, family, substance use, trauma, legal, educational, and vocational domains. Administer appropriate screening tools such as PHQ-9 for depression, GAD-7 for anxiety, and PC-PTSD-5 for trauma exposure. Conduct a mental status exam. Screen for suicidal and homicidal ideation. Review current medications and medical conditions. Identify client strengths and support systems. Begin to identify treatment goals collaboratively with the client.</p><p><strong>Documentation Required:</strong> Intake assessment form, signed consent, preliminary DSM-5-TR diagnoses, risk assessment note, and a treatment plan draft to be completed by session 3. Billing: 90791 (psychiatric diagnostic evaluation) or equivalent intake code per your agency guidelines.</p>',
            ],
            [
                'title_suffix' => 'Visit 2 – Treatment Planning and Skill Building',
                'description'  => '<p><strong>Session Context:</strong> The counselor and client collaboratively review and formalize the treatment plan. This session introduces psychoeducation and initial skill-building interventions matched to the identified clinical needs. The therapeutic alliance is deepening. The counselor reinforces and validates the client experience while beginning to challenge maladaptive cognitions or behaviors as clinically appropriate given theoretical orientation and treatment goals.</p><p><strong>Key Counselor Tasks:</strong> Review any homework or between-session observations from the initial session. Provide psychoeducation on the client diagnosis and the treatment rationale. Introduce the cognitive model (if using CBT), attachment-based concepts (if using EFT), or a psychodynamic formulation as appropriate. Collaboratively set SMART goals — Specific, Measurable, Achievable, Relevant, and Time-bound. Introduce coping strategies appropriate to the presenting problem such as diaphragmatic breathing for anxiety, behavioral activation for depression, or grounding techniques for trauma. Assess client understanding and motivation for change using Motivational Interviewing techniques including open questions, affirmations, reflections, and summaries. Address ambivalence. Review medication compliance if applicable. Document progress note using DAP or SOAP format.</p><p><strong>Coordination Considerations:</strong> Consider consultation with prescribing physician if medication changes are indicated. Coordinate with case manager or school counselor if client is a minor. Assess need for higher level of care (intensive outpatient, partial hospitalization) if symptoms are not stabilizing as expected.</p>',
            ],
            [
                'title_suffix' => 'Visit 3 – Progress Review and Termination Planning',
                'description'  => '<p><strong>Session Context:</strong> This session marks a significant juncture in the treatment trajectory. The counselor evaluates the client progress against treatment plan goals, addresses any remaining barriers, consolidates gains, and begins discussion of termination or step-down care. This visit is critical for relapse prevention planning and ensuring appropriate continuity of care upon discharge.</p><p><strong>Key Counselor Tasks:</strong> Administer progress-monitoring measures such as re-administering the PHQ-9 or the Outcome Rating Scale (ORS). Review goal attainment collaboratively: identify what has improved, what remains unresolved, and what new challenges may have emerged. Explore the client experience of the therapeutic relationship, including any ruptures and repairs that occurred during treatment. Introduce relapse prevention planning: identify early warning signs, build a coping skills inventory, develop a support system activation plan, and review crisis resources. Discuss the termination timeline if the client has met goals and process both partners emotional responses to ending — which may include dependency, abandonment fears, ambivalence, or pride in growth. If goals are not yet met, revise the treatment plan accordingly. Provide referrals as needed to psychiatry, support groups, community resources, or a higher level of care. Summarize progress in clinical terms for documentation and potential insurance review. Review discharge criteria and aftercare plan. Conduct a final risk assessment. Complete any outstanding documentation including discharge summary if ending or updated treatment plan if continuing care.</p><p><strong>Ethical Considerations:</strong> Ensure informed consent for any referrals made. Discuss duty to warn obligations if new risks have emerged during the course of treatment. Follow mandated reporting protocols if child or elder abuse disclosures occurred. Maintain accurate and timely documentation to protect client welfare and safeguard counselor licensure in accordance with applicable state regulations and professional ethical codes (ACA Code of Ethics, NBCC standards).</p>',
            ],
        ];
    }

    public function run(): void
    {
        $this->command->info('Updating Case Studies and Visits with realistic clinical content...');

        $caseStudies   = CaseStudy::orderBy('id')->get();
        $scenarios     = $this->getCaseStudies();
        $visitTemplates = $this->getVisitTemplates();

        if ($caseStudies->isEmpty()) {
            $this->command->error('No case studies found! Please run the exam seeder first.');
            return;
        }

        $csCount = count($scenarios);

        foreach ($caseStudies as $index => $cs) {
            $scenario = $scenarios[$index % $csCount];

            $cs->update([
                'title'   => $scenario['title'],
                'content' => $scenario['content'],
            ]);

            $visits = Visit::where('case_study_id', $cs->id)->orderBy('order_no')->get();

            foreach ($visits as $vIdx => $visit) {
                $template = $visitTemplates[$vIdx % count($visitTemplates)];

                $visit->update([
                    'title'       => $scenario['title'] . ' – ' . $template['title_suffix'],
                    'description' => $template['description'],
                ]);
            }

            $this->command->info("  Updated: [{$cs->id}] {$scenario['title']} with {$visits->count()} visit(s)");
        }

        $this->command->info('All Case Studies and Visits updated successfully!');
    }
}
